### ISSUE TITLE
SRS Review: Grammar/Formatting Master List

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#10]
The following is a list of grammar, formatting, etc. issues that weren't in sections with another issue in them or that were in sections with only one other issue in them.

# TODO
*Any point that requires more discussion should be pulled out to a different issue.*

- [x] I think your subtitle should start with a capital letter, and I'm not sure it should have a period.
- [x] Throughout the document, it should either be "2D" or "two-dimensional", not "2-dimensional".
- [x] In Subsection 2.1, I think "so (that)" would be a better word choice than "such that" in "The document provides sufficient information such that...."
- [x] In Subsection 2.1, "increased" doesn't need quotation marks, as you immediately justify why the "degree of confidence in reliability and correctness" is increased.
- Not a critique, but I could almost audibly hear you say "adequately codified". 😂
- [x] In Subsection 2.2, "subsection 4.1" should be capitalized.
- [x] In Subsection 2.2, since you define what the problem is, or at least where to find it, you should also define what the solution will be (i.e., "the program specified by this document", etc.); I am unsure if the quotation marks around "problem" and "solution" are necessary.
- [x] In Subsection 3.1, verb tenses for responsibilities should be consistent (e.g., "Providing" vs. "Interpret").
- [x] In Subsection 3.2, consider using "...applied in educational contexts..." or "...applied for educational purposes...."
- [x] In Subsection 3.2, there shouldn't be a hyphen in "simply-supported".
- [x] In Subsection 4.1, "...deflection experience by the beam..." might be more clear.
- [x] I think "Detailed derivation of simplified rate of change of temperature" in Subsection 4.2.3 is a mistake.

**Comment by balacij** [comment]
1. :heavy_check_mark: 
2. :heavy_check_mark: 
3. :heavy_check_mark:
4. I think I should keep the quotation marks because it's not really talking about something we can quantify. Perhaps I'm being too pedantic?
5. :rofl: 
6. :heavy_check_mark:
7. :heavy_check_mark:
8. :heavy_check_mark:
9. :heavy_check_mark:
10. :heavy_check_mark: In all honesty, I have a nagging feeling that "simply supported" should be "simply-supported" in Canadian English.
11. :heavy_check_mark: 
12. :heavy_check_mark:

Thank you very much :smile:

**Comment by balacij** [comment]
Closed in fe02e8933199ef6e160f150e098ab9305b068a6c

**Comment by samm82** [comment]
In [Canadian English](https://www.btb.termiumplus.gc.ca/tcdnstyl-chap?lang=eng&lettr=chapsect2&info0=2) (and [American English](https://www.grammarly.com/blog/hyphen/) as well), adjectival phrases made of an adverb ending in "ly" and an adjective are **not** hyphenated. I don't really like it either, but what can you do? ¯\\\_(ツ)_/¯

**Comment by samm82** [comment]
Also, regarding point 4, I would argue that you can still increase things that can't be quantified (like understanding, trust, etc.) and that this process is well-understood enough to not merit quotation marks.

**Comment by balacij** [comment]
Re. English: lol, thanks for looking it up!

Re. 4: I agree, it's just not quantifiable. Since the document is intended to be completely correct, I feel the need to be completely correct too, so I'll just keep the caveat footnote and remove the quotation marks. I'm probably still being pedantic, nbd, I'll re-evaluate when I re-write the SRS in Drasil.
