### ISSUE TITLE
SRS Review: Terminology and Definitions section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#12]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The list of terms should be sorted alphabetically for ease of navigation.
- [x] Make sure the plurality of each term matches its definition. For example, since "beam" is singular, its definition should be too: "structural component~~s~~ intended...."
   - [x] Related: either all terms should be singular or all terms should be plural for consistency.
- [x] There shouldn't be a comma in the definition of simply supported beam.
- [x] Your examples for shear forces are really examples of things that _exert_ shear forces, not the forces themselves; this could be made more clear or different examples could be used.
- [x] "Modulus of elasticity" should be listed as a separate definition in case the reader is looking for it alphabetically, doesn't find it, and gives up. The definition of "Young's modulus" should then point to the definition of "modulus of elasticity."
- [x] Most terms start with "the", but some done (e.g., "moment of inertia").
