### ISSUE TITLE
SRS Review: Physical System Description

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#13]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] "At-rest" doesn't need quotations.
- [x] The list of elements in the figure is duplicated in the list of components in the physical system; consider removing the first list.
- [x] You use the subjective word "slender"; either use a more precise word or define it in the Terminology and Definitions section.
- [x] You also use the word "determinant" and italicize it; since it is so significant, you should define it as well.

**Comment by balacij** [comment]
1. :heavy_check_mark: 
2. :heavy_check_mark: 
3. I had it defined in the assumptions, but it's a good idea to move it to the TnD section. :heavy_check_mark: 
4. Added a citation. :heavy_check_mark: 

Thanks!

Closed in c555d0ab894ae194ef6d0935f65bb41b43c7e687
