### ISSUE TITLE
SRS Review: Goal Statements Section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#14]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The list of inputs seems ambiguous. There should be a "the" in front of each input; without it, it implies that the constant length and modulus of elasticity are also across cross-sections of the beam as well (which might be the case; if so, there should only be a "the" in front of "constant length").
- [x] There shouldn't be a comma after "beam".
- [x] What is the point of calculating the reaction of the supports under load? If it is outputted to the user, it should be in the System Context section.

**Comment by balacij** [comment]
1. I just put the "of moment ..." bit in parentheses. I think that solves it?
2. :heavy_check_mark: 
3. I removed this goal altogether.

Closed in c8a5a64b1c7b5a21a7a417a4deef992eaf7e7b71

**Comment by samm82** [comment]
I think so - I realized that you could also remove the parentheses if you also remove the first "and".
