### ISSUE TITLE
SRS Review: TMs

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#17]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] Should the citation of TM1 be moved to after the description of the variables?
- [x] Description missing for TM3.
- [x] You say "Derivation for TM3" is "Not Applicable", then supply it below.
- [x] In the derivation (?) of TM4, either use parenthetical commas or parentheses when naming $w(x)$, not both.
- [x] #67

**Comment by balacij** [comment]
Thanks! This was sporadically fixed (across commits).
