### ISSUE TITLE
SRS Review: FRs

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#21]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] "End-user" (and related words) only have a hyphen when they are an adjective, not a noun.
- [x] What does "meaningful" mean in R2?
- [x] There isn't any requirement for the BVP solver; does input need to be formatted to use it?
- [x] What does "well-defined" mean in R4?

**Comment by balacij** [comment]
2) Meaningful just means nontrivial, really. So, post-validation.
3) I don't want to constrain implementation. I will leave it up to the software design guide.

Thanks!
