### ISSUE TITLE
SRS Review: NFRs

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#22]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] What is the "level [of accuracy] needed for civil engineering? A source might be helpful here.
- [ ] It should be "visualization" and "reiterating".
- [ ] What does it mean to reiterate information? Are these additional outputs?
   - [ ] What does "important" information entail?
- [ ] What do the phrases "relatively straightforward and already well-understood" and "clear impact" mean in NFR3?

**Comment by balacij** [comment]
1. I re-phrased to mention "applicable regulatory bodies" to completely avoid discussing ambiguous "levels."
2. :heavy_check_mark: 
3. Repeating the inputs, and no. It's just reiterating the inputs to the program. I'm not sure if Drasil does this yet though.  I changed this so that it avoids ambiguous "important."
4. It just means that all likely changes should be restricted to those that Drasil can actually handle (i.e., no functionality hacking). Clear impact means we can unambiguously analyze the impacts of a particular change (right now, this is Haskell and Drasil+Drasil tools itself that does it for us)

Thanks again!
