### ISSUE TITLE
Issues related to section 4 till 9:

### ISSUE THREAD

**Issue by MinMah23** [balacij/Drasil#25]
- [x] As Prof. Smith told when you were presenting, It's better to use appropriate arrow to show rotations on figure 2.
- [x] The word "slender" used in section 4.1.2 without prior definition, however the definition is in assumption A2, It should be added to Terminology section. #13 
- [x] I didn't get the way A9 and A10 in assumptions are written.
- [ ] TM3 needs description to be added. #17
- [ ] In TM3, You show how TM# is derived from TM1 and A8, so the "Derivation for TM3" is applicable.
- [x] The sources and Ref.By  parts in IM1 are missed.#18
- [ ] I saw the issue#20, however I think it's better to consider what Prof. Smith told to me, "For a section of a template, if you don't use it, keep the title and enter "Not applicable". If it isn't obvious, explain why the section is not applicable. I don't think I explicitly mentioned this in class, but with a standard template you don't want to delete sections. If someone reads the document and a section is missing, they don't know if the author forgot the section, or intentionally removed it." In fact, the quotation was about the whole section but I think we can apply the same way for the subsections too.
- [x] In NFR1 and 2, you refer to Section X of V&V plan which is not written yet. They are relatively ambiguous.
- [ ] Table 4 in section 8, should be revised, as it is like a symmetric matrix, but your table is not and should be completed.
Thanks.

**Comment by balacij** [comment]
Regarding A9 and A10, I think they are the now A15 and A16. I'm not quite sure what's confusing about it, can you elaborate please?

![Screenshot from 2023-03-16 16-41-58](https://user-images.githubusercontent.com/1627302/225747910-f49bf250-358b-4d96-bbdb-5e05b174f0d1.png)

**Comment by balacij** [comment]
@samm82 commented on it on #15.

**Comment by balacij** [comment]
Thank you! I think I got to the majority of this in earlier commits (lost in the history), but the 'final' commit that complets this is 3d73005bd.
