### ISSUE TITLE
VnV Plan Review: Symbols, Abbreviations, and Acronyms section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#29]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] "Symbols, Abbreviations, and Acronyms" shouldn't be capitalized in the paragraph before the table.
- [x] I think saying "SRS document" is redundant; I would just say "SRS".

## Personal Preference
- [ ] I think the description of "CAS" should just be "Computing and Software", since that is what it stands for. This is a little tricky, since there isn't a Terminology and Definitions section like in the SRS where more detailed information could be captured, so this is up to you.
- [x] I would be more explicit about which symbols, etc. are used in the VnV (something like "In addition to the ones from the SRS, the following symbols, etc. are used in this document.").

**Comment by balacij** [comment]
I definitely wrote "SRS document" a lot.... Lol! Thank you :smile: 

b917d4d9c
