### ISSUE TITLE
SRS Review: Issues with Table of Symbols

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#3]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] The sentence "The choice of symbols was made to be consistent with the heat transfer literature and with existing documentation for solar water heating systems." is borrowed from the template and does not reflect your project. 
- [x] You say "The symbols are listed in alphabetical order," but they are not.
- [x] Subscripts with words should not be italicized (i.e., `R_{\text{Pinned}}`).
- [x] Consider an alternate way to display/name "Pinned" and "Roller"; perhaps change their names or use `\text{}` for them as well, since they are words and not variables (P\*i\*n\*...).
- ~~[From what I can tell](https://math.stackexchange.com/questions/471017/help-with-proof-hyperplane-is-an-n-1-dimensional-linear-variety), "n+1-dimensional" should be formatted as "(n+1)-dimensional" to be more clear.~~
- [ ] The following symbols are missing: $\rho$, $x$ and $y$ (in the context of TM1), $M(x)$, and $EI$.

**Comment by balacij** [comment]
You're definitely correct that I didn't add all symbols to the table of symbols. `x`, `y`, `E`, and `I` are there now. I'll need to add the others too.

Aside: I currently have `E` and `E_B`. `E` is meant to be a hypothetical variable (without a value), while `E_B` is meant to be the one provided by users and have a concrete value. I haven't yet responded to @smiths feedback regarding this, but it seems relevant here :smile: 

On the note of the table of symbols: do we want all symbols to be in the global table of symbols? I think it would be nice to have some symbols (such as `E` and `I` here) made and displayed locally in their respective theories because they don't leak into the instance models (I have `E_B` and `I_B` for the instance models). What do we think about having the global table of symbols only carry the symbols "local" to all instance models involving the inputs and outputs? 

Pinging @smiths too.

**Comment by smiths** [comment]
I don't believe that Drasil allows for local symbols.  I'm fairly sure that all of the symbols go to the global table of symbols.  In the long run, we shouldn't do this.  We'll have too many symbol clashes once we get to more complex problems.  We also have the problem of mixing symbols that are only used once with symbols that are used multiple times.

In answer to your question @balacij, for symbols that are only used locally, you can define them locally and not include them in the global table of symbols.  You can do this for your manual SRS.  I'm not 100% sure you'll be able to do it for the Drasil SRS.

**Comment by balacij** [comment]
Sounds good, thank you @smiths! Hopefully we can figure out how to build scopes in Drasil at some point. I haven't been able to come up with a good solution yet.
