### ISSUE TITLE
VnV Plan Review: General Information section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#30]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] "Beam Bending" shouldn't be capitalized in the General Information section.
- [x] I would be a bit more specific about the purpose of verification (something like "...and verifying that a software built following the SRS actually satisfies the listed requirements."); the sentence as-is is quite confusing and unclear.
- [x] There shouldn't be a comma after "imposed" in the Summary section.
- [x] There shouldn't be a hyphen in "simply supported".
- [x] There seems to be duplication between the General Information section and the Objectives section; maybe remove the descriptions of validation and verification from the General Information section?
- [x] There shouldn't be a comma after "requirements" in the last sentence of the Objectives section.
   - [x] This sentence is also quite confusing; consider rewriting it for clarity.
- [x] The documentation generated by Drasil (e.g., the generated SRS and, if you decide to count them, code comments) is also relevant; this documentation should be added to the list, even if it does not exist yet.
- [x] The last sentence of the Relevant Documentation section should say "...that we can **add** to the above list" (or something similar).

**Comment by balacij** [comment]
Cheers, thanks! d3ea8b581
