### ISSUE TITLE
VnV Plan Review: Content of Verification and Validation Team section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#31]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] Is it intentional to include "domain expert" in the Supervisor role when it is its own separate role?
   - [ ] If so, remove the "and" before "distinguished reviewer" in the Supervisor description and add the Oxford comma to be consistent with the rest of the document.
- [ ] The description of the Author role is not really informative.
- [ ] The Verifier and Validator roles seem restricted in scope. They should also involve the verification and validation of the code itself when created.
- [ ] Are you also a domain expert?
- [ ] Maryam's project is really the Drasil implementation, not Drasil itself.
- [ ] The class members aren't supervisors, so they shouldn't have all roles.
- [ ] The description of the "*" should be more fleshed-out.

**Comment by balacij** [comment]
1. Thanks, I fixed it!
2. Right, I gave it another go. It's mostly self-explanatory, but needed regardless.
3. For the purposes of the course, I was thinking that the majority of their work should be restricted to the encoding in Drasil. The encoding of the SRS + knowledge in Drasil should accurately depict the manually created SRS. Once I have code generation going, I think we can open up the scope, but I think it would be a tall order to ask anyone to review a (newly designed) code generation scheme for the BVP.
4. Ironically, no (lol!). Even though I've written the project, my understanding of all of the concepts is still fairly shallow. I'm confident both you and @smiths have a deeper understanding of the theory than I do.
5. LOL! Yes, you're right :smile:
6. I had a kind of "trial by fire" mindset with that thought. I think you're right though.
7. Cheers, I tried to fix it now.

bbc752e3a
