### ISSUE TITLE
VnV Plan Review: Verification Plans/Tools sections

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#32]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] Who will be the one "checking that BeamBending’s Software Requirements Specification (SRS) conforms to Dr. Smith’s provided SRS checklist"?
- [x] I don't think that the phrase "The software design does not need verification..." is correct. The software design should be verified, but it's OK if that is left to the Drasil team (as the validation is).
- [x] Who are the "many eyes" or the "team member[s]" who will be looking over the VnV? Everyone in your Table of VnV Teammates? Only some of them will be looking at the VnV.
- [x] It seems weird to me that the "many eyes" hypothesis is only introduced for the VnV Plan and not other artifacts. 
- [x] In the Implementation Verification Plan section, should it say "The generated software artifacts should be tested against the manually created artifacts **to see if** if non-trivial or significant differences exist;" presumably you will be testing the generated version against the manual one even if there aren't major differences.
- [x] You should explain why "we have faith in the Drasil work."
- [x] What does "aggressively formatt[ing]" the Python code entail?

**Comment by balacij** [comment]
2. The part after the "..." defers the onus of verification to the Drasil team :)
3/4. "many eyes" as in [Linus's Law](https://en.wikipedia.org/wiki/Linus%27s_law) but also as in psychology, it's an oddly common thing, I'll add another citation (this time to Linus's Law) to better explain it.
7. Ah, that was meant to be in quotation marks. Python Black is an opinionated formatter which does has few options.

Thanks! 5e879fd35
