### ISSUE TITLE
VnV Plan Review: Grammar/formatting of Plan section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#33]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] This section doesn't need to be on its own page.
- [x] Including '"whole"' before "Verification and Validation plan" isn't necessary; the plan should be complete, but even if it isn't, this should be "faked" as per the documentation process.
- [x] "Responsibilities" should be capitalized in the Table of VnV Roles.
- [x] For consistency, configuration requirement 1c should be "**with** “full” modularity."
- [x] Since other new terms/technologies aren't bolded on their first introduction, neither should "pytest."
- [x] The phrase "the author" in the Software Validation Plan section is ambiguous since you introduce the hypothetical writer of a textbook in the previous sentence. Maybe say "the author of this document" instead?

## Personal Preference
- [x] According to Wiktionary, "[subplan](https://en.wiktionary.org/wiki/subplan)" and "[subteam](https://en.wiktionary.org/wiki/subteam)" don't have hyphens, but I don't think it is incorrect to keep them.
- [x] Likewise, "[nontrivial](https://en.wiktionary.org/wiki/nontrivial#Usage_notes)" also shouldn't have a hyphen.
- [x] I would say "the unit tests will be **performed on** the generated software artifacts" instead of "the unit tests will be ported over to the generated software artifacts."

**Comment by balacij** [comment]
Interestingly, my grammar checker complains about "sub-plan" but prefers "subteam", saying that "sub-plan" does not exist! I've changed it to avoid referring to "sub-plan" entirely.

Thank you! 9b225d71e

**Comment by samm82** [comment]
The good ol' "writing a paper" approach of just rewriting it 😂
