### ISSUE TITLE
VnV Plan Review: Tests for Nonfunctional Requirements section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#35]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [ ] Your test cases for the NFRs should be rephrased to describe the process of verifying them instead of describing why they are verified.
- [x] Your test for accuracy does not satisfy your NFR for accuracy.
- [x] "Three" should be spelled out (also in the SRS).
- [ ] Your usability test should direct to the Usability Survey Questions section of the appendix.
   - [ ] Related: if you are not testing for accessibility, than you should omit accessibility from the Usability Survey Questions section.
- [ ] "[Regeneration](https://www.merriam-webster.com/dictionary/re-generation)" does not have a hyphen.

**Comment by balacij** [comment]
1. I'm deferring a lot of the work to Drasil and the encoding of the SRS holding true to the manually created one. I think there might be room to discuss what makes the encoding accurate, but that's not really what this part is about.
4. I think this review was made early? I do not have accessibility mentioned in that section.
5. Neat!
32b22f904
