### ISSUE TITLE
SRS Review: Issues in Introduction paragraphs

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#5]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] Many sentences make claims that should be backed up (e.g., "For any structure carrying load, beams are used to...", "Unlike flooring in residential homes, we expect..."). These might be common knowledge to a domain expert, such as the intended reader of the document, so Dr. Smith might need to weigh in on this one.
- [x] There is likely other software that can be used to "analyze the beams reaction under various loading scenarios", so it sounds a little presumptuous to say "We call the software that performs this, 'BeamBending,'" as if it is and will be the only piece of software to do this.
- [x] It should be "We call the software that performs this 'BeamBending,'" without the colon.
- [x] You define what a "simply supported beam" is but never reference it again; will BeamBending focus on simply supported beams?

**Comment by balacij** [comment]
Thanks! Fixed in 49ba0d43c, but I also edited the other components in earlier commits.
