### ISSUE TITLE
SRS Review: Issues with Characteristics of Intended Reader section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#6]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] [Drasil](https://jacquescarette.github.io/Drasil/examples/ssp/SRS/srs/SSP_SRS.html#Sec:ReaderChars) currently uses "undergraduate level 2", etc. to refer to levels of post-secondary education; you might consider doing this for consistency.
- [x] I'm not sure that the necessary concepts from physics need to be explicitly described, since a lot of them seem trivial.
   - [x] I'm conflicted about this, since I'm not sure if I learned about elasticity in first-year physics.
- [x] If included, the necessary concepts from physics do not need quotation marks.
- [x] [Drasil](https://jacquescarette.github.io/Drasil/examples/ssp/SRS/srs/SSP_SRS.html#Sec:ReaderChars) also uses "It would be an asset to understand _" to introduce unrequired but beneficial knowledge; you might consider doing this for consistency.
- [x] The final sentence should be more explicit. What does "non-trivial" mean? If an engineering student tries to build a structure, is that OK since it is experiential learning (and thus not "non-educational")? I'm not sure if the reading of this document can/should be restricted.

**Comment by balacij** [comment]
1. Sounds good.
2. Good catch. While I don't think I learned about elasticity in first-year physics, I prefer to remove it because I hope that one day the noun will refer to a well-defined set of things that users can look into on their own.
3. N/a.
4. I like it.
5. experiential learning is still done in the context of research with simplified conditions, it wouldn't be used for live-users for example, so I would still call it "educational". This line was something I thought to write assuming the document would be read by others, outside the context of the class. I re-wrote it, but, either way, I think we would want to have _something_ about liability and warranty.

Closed in fbe05f9838fbc7ca7556f2409271c0ca3b7b668c, thank you!

**Comment by smiths** [comment]
Elasticity isn't covered in first-year physics.  I learned it in a second-year engineering mechanics course.  I'm fairly certain that this is standard.  First year is rigid body mechanics and second year is where it is typically introduced that bodies can actually deform.  (Elasticity is the simplest constitutive equation for modelling the deformation of solids.)
