### ISSUE TITLE
SRS Review: Issues with System Context section

### ISSUE THREAD

**Issue by samm82** [balacij/Drasil#8]
# TODO
*Any point that requires more discussion should be pulled out to a different issue; I grouped these all here since they are related and small.*

- [x] I'm also not sure if the adjective "provided" in the System Context paragraph is needed. If you decide to keep it, you should explain what it means: who is providing it? This would likely mean adding something to the System Constraints section.
- [x] "BeamBending" shouldn't be in quotation marks, since it is an established term in the document.
- [x] There shouldn't be a comma after inputs in the last sentence, since there are only two items in the list ("use a provided..." and "output the ...curve."
- [x] The inputs and outputs to the BVP could be specified more: what data gets sent to the solver?
- [x] Since you are using an external Boundary Value Problem solver, it should have its own associated responsibilities.

**Comment by balacij** [comment]
1. Originally, I intended for users to provide one of their own, but it doesn't make much sense. Good catch!
2. Oops!
3. Thanks! I overuse punctuation.
4. The data isn't actually clear yet, it's mostly up to the software design, whether it chooses to use symbolic or numerical solving methods. If I try to keep it abstract, then I can only think of "BVP information" as an input, which seems a bit too obvious (?). Any ideas?
5. Thanks!

Closed in e07415acb554db69c7351b758c078c652f087a17

**Comment by smiths** [comment]
Item 4 is interesting.  It highlights the way we have faked the gap between requirements and code.  The SRS doesn't really have to mention this information, or even the fact that we are using a BVP solver.  However, the code generation wants this.  Since we don't have a document between the SRS and the code, the idea of "BVP information" as an abstraction seems good to me.

**Comment by balacij** [comment]
Cheers! I added another small blurb next to the arrow. Thank you both! :smile: 

dfb4b65bbd6b7930864a289f1429b755efdc5b2b
